# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x02pb\"\x1e\n\x0e\x41nalyseRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"f\n\x0f\x41nalyseResponse\x12\x13\n\x0b\x61ll_account\x18\x01 \x01(\x05\x12\x0e\n\x06level0\x18\x02 \x01(\x05\x12\x0e\n\x06level1\x18\x03 \x01(\x05\x12\x0e\n\x06level2\x18\x04 \x01(\x05\x12\x0e\n\x06level3\x18\x05 \x01(\x05\"\x1e\n\x0cTrainRequest\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\" \n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\tDatainput\x12\x15\n\rclocationinfo\x18\x01 \x01(\t\"2\n\x0c\x41lertRequest\x12\"\n\x0b\x64\x61tarequest\x18\x01 \x03(\x0b\x32\r.pb.Datainput\"#\n\nDataoutput\x12\x15\n\rclocationinfo\x18\x01 \x01(\t\"5\n\rAlertResponse\x12$\n\x0c\x64\x61taresponse\x18\x01 \x03(\x0b\x32\x0e.pb.Dataoutput2\x9c\x01\n\x04\x63ore\x12\x34\n\x07\x41nalyse\x12\x12.pb.AnalyseRequest\x1a\x13.pb.AnalyseResponse\"\x00\x12.\n\x05Train\x12\x10.pb.TrainRequest\x1a\x11.pb.TrainResponse\"\x00\x12.\n\x05\x41lert\x12\x10.pb.AlertRequest\x1a\x11.pb.AlertResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANALYSEREQUEST._serialized_start=18
  _ANALYSEREQUEST._serialized_end=48
  _ANALYSERESPONSE._serialized_start=50
  _ANALYSERESPONSE._serialized_end=152
  _TRAINREQUEST._serialized_start=154
  _TRAINREQUEST._serialized_end=184
  _TRAINRESPONSE._serialized_start=186
  _TRAINRESPONSE._serialized_end=218
  _DATAINPUT._serialized_start=220
  _DATAINPUT._serialized_end=254
  _ALERTREQUEST._serialized_start=256
  _ALERTREQUEST._serialized_end=306
  _DATAOUTPUT._serialized_start=308
  _DATAOUTPUT._serialized_end=343
  _ALERTRESPONSE._serialized_start=345
  _ALERTRESPONSE._serialized_end=398
  _CORE._serialized_start=401
  _CORE._serialized_end=557
# @@protoc_insertion_point(module_scope)
